#!/usr/bin/env python
# -*-coding:utf-8 -*-
'''
Author Tim Maniquet

- Name useful directories
- Create palette for ROIs and categories
- List all images in their number and category order

Created 2026/01/14 16:42:48
'''

import os

# Data directories
data_dir = 'data'
brain_data_dir = os.path.join(data_dir, 'brain_data')
dnn_data_dir = os.path.join(data_dir, 'dnn_data')
ratings_data_dir = os.path.join(data_dir, 'ratings_data')
basic_rt_data_dir = os.path.join(data_dir, 'basic_rt_data')
basic_motor_data_dir = os.path.join(data_dir, 'basic_motor_data')
animacy_motor_data_dir = os.path.join(data_dir, 'animacy_motor_data')
category_membership_dir = os.path.join(data_dir, 'category_membership')
auc_dir = os.path.join(data_dir, 'motor_auc')

# Output directories
figure_dir = os.path.join('figures')
figure_ext = 'png'

# Maximum plotting time for trajectories
max_t = 1000

# Lists and dictionaries
rois = [
    "ffa",
    "ofa",
    "eba",
    "ppa"
]
category_to_animacy = {
    "face": "animate",
    "body": "animate",
    "object": "inanimate",
    "scene": "inanimate"
}
categories = [
    "face",
    "body",
    "object",
    "scene"
]
palette = {
    "body": "orange",
    "face": "red",
    "object": "dodgerBlue",
    "scene": "green",
    "animate": "darkorange",
    "inanimate": "mediumpurple",
    "ffa": "red",
    "ofa": "red",
    "ppa": "green",
    "eba": "orange"
}
preferred_categories = {
    "face": ["ffa", "ofa"],
    "body": ["eba"],
    "scene": ["ppa"],
}
roi_to_category = {
    "ffa": "face",
    "ofa": "face",
    "eba": "body",
    "ppa": "scene"
}
images_category_ordered = [
    "main_face_26",
    "main_face_27",
    "main_face_28",
    "main_face_29",
    "main_face_30",
    "main_face_31",
    "main_face_32",
    "main_face_33",
    "main_face_34",
    "main_face_35",
    "main_face_36",
    "main_face_37",
    "main_face_38",
    "main_face_39",
    "main_face_40",
    "main_face_41",
    "main_face_42",
    "main_face_43",
    "main_face_44",
    "main_face_45",
    "main_face_46",
    "main_face_47",
    "main_face_48",
    "main_face_49",
    "main_face_50",
    "main_body_1",
    "main_body_2",
    "main_body_3",
    "main_body_4",
    "main_body_5",
    "main_body_6",
    "main_body_7",
    "main_body_8",
    "main_body_9",
    "main_body_10",
    "main_body_11",
    "main_body_12",
    "main_body_13",
    "main_body_14",
    "main_body_15",
    "main_body_16",
    "main_body_17",
    "main_body_18",
    "main_body_19",
    "main_body_20",
    "main_body_21",
    "main_body_22",
    "main_body_23",
    "main_body_24",
    "main_body_25",
    "main_body_101",
    "main_body_102",
    "main_body_103",
    "main_body_104",
    "main_body_105",
    "main_body_106",
    "main_body_107",
    "main_body_108",
    "main_body_109",
    "main_body_110",
    "main_body_111",
    "main_body_112",
    "main_body_113",
    "main_body_114",
    "main_body_115",
    "main_body_116",
    "main_body_117",
    "main_body_118",
    "main_body_119",
    "main_body_120",
    "main_body_121",
    "main_body_122",
    "main_body_123",
    "main_body_124",
    "main_body_125",
    "main_object_51",
    "main_object_52",
    "main_object_53",
    "main_object_54",
    "main_object_55",
    "main_object_56",
    "main_object_57",
    "main_object_58",
    "main_object_59",
    "main_object_60",
    "main_object_61",
    "main_object_62",
    "main_object_63",
    "main_object_64",
    "main_object_65",
    "main_object_66",
    "main_object_67",
    "main_object_68",
    "main_object_69",
    "main_object_70",
    "main_object_71",
    "main_object_72",
    "main_object_73",
    "main_object_74",
    "main_object_75",
    "main_object_151",
    "main_object_152",
    "main_object_153",
    "main_object_154",
    "main_object_155",
    "main_object_156",
    "main_object_157",
    "main_object_158",
    "main_object_159",
    "main_object_160",
    "main_object_161",
    "main_object_162",
    "main_object_163",
    "main_object_164",
    "main_object_165",
    "main_object_166",
    "main_object_167",
    "main_object_168",
    "main_object_169",
    "main_object_170",
    "main_object_171",
    "main_object_172",
    "main_object_173",
    "main_object_174",
    "main_object_175",
    "main_object_176",
    "main_object_177",
    "main_object_178",
    "main_object_179",
    "main_object_180",
    "main_object_181",
    "main_object_182",
    "main_object_183",
    "main_object_184",
    "main_object_185",
    "main_scene_76",
    "main_scene_77",
    "main_scene_78",
    "main_scene_79",
    "main_scene_80",
    "main_scene_81",
    "main_scene_82",
    "main_scene_83",
    "main_scene_84",
    "main_scene_85",
    "main_scene_86",
    "main_scene_87",
    "main_scene_88",
    "main_scene_89",
    "main_scene_90",
    "main_scene_91",
    "main_scene_92",
    "main_scene_93",
    "main_scene_94",
    "main_scene_95",
    "main_scene_96",
    "main_scene_97",
    "main_scene_98",
    "main_scene_99",
    "main_scene_100",
    "main_scene_126",
    "main_scene_127",
    "main_scene_128",
    "main_scene_129",
    "main_scene_130",
    "main_scene_131",
    "main_scene_132",
    "main_scene_133",
    "main_scene_134",
    "main_scene_135",
    "main_scene_136",
    "main_scene_137",
    "main_scene_138",
    "main_scene_139",
    "main_scene_140",
    "main_scene_141",
    "main_scene_142",
    "main_scene_143",
    "main_scene_144",
    "main_scene_145",
    "main_scene_146",
    "main_scene_147",
    "main_scene_148",
    "main_scene_149",
    "main_scene_150"
    ]
images = [
    "main_body_1",
    "main_body_2",
    "main_body_3",
    "main_body_4",
    "main_body_5",
    "main_body_6",
    "main_body_7",
    "main_body_8",
    "main_body_9",
    "main_body_10",
    "main_body_11",
    "main_body_12",
    "main_body_13",
    "main_body_14",
    "main_body_15",
    "main_body_16",
    "main_body_17",
    "main_body_18",
    "main_body_19",
    "main_body_20",
    "main_body_21",
    "main_body_22",
    "main_body_23",
    "main_body_24",
    "main_body_25",
    "main_face_26",
    "main_face_27",
    "main_face_28",
    "main_face_29",
    "main_face_30",
    "main_face_31",
    "main_face_32",
    "main_face_33",
    "main_face_34",
    "main_face_35",
    "main_face_36",
    "main_face_37",
    "main_face_38",
    "main_face_39",
    "main_face_40",
    "main_face_41",
    "main_face_42",
    "main_face_43",
    "main_face_44",
    "main_face_45",
    "main_face_46",
    "main_face_47",
    "main_face_48",
    "main_face_49",
    "main_face_50",
    "main_object_51",
    "main_object_52",
    "main_object_53",
    "main_object_54",
    "main_object_55",
    "main_object_56",
    "main_object_57",
    "main_object_58",
    "main_object_59",
    "main_object_60",
    "main_object_61",
    "main_object_62",
    "main_object_63",
    "main_object_64",
    "main_object_65",
    "main_object_66",
    "main_object_67",
    "main_object_68",
    "main_object_69",
    "main_object_70",
    "main_object_71",
    "main_object_72",
    "main_object_73",
    "main_object_74",
    "main_object_75",
    "main_scene_76",
    "main_scene_77",
    "main_scene_78",
    "main_scene_79",
    "main_scene_80",
    "main_scene_81",
    "main_scene_82",
    "main_scene_83",
    "main_scene_84",
    "main_scene_85",
    "main_scene_86",
    "main_scene_87",
    "main_scene_88",
    "main_scene_89",
    "main_scene_90",
    "main_scene_91",
    "main_scene_92",
    "main_scene_93",
    "main_scene_94",
    "main_scene_95",
    "main_scene_96",
    "main_scene_97",
    "main_scene_98",
    "main_scene_99",
    "main_scene_100",
    "main_body_101",
    "main_body_102",
    "main_body_103",
    "main_body_104",
    "main_body_105",
    "main_body_106",
    "main_body_107",
    "main_body_108",
    "main_body_109",
    "main_body_110",
    "main_body_111",
    "main_body_112",
    "main_body_113",
    "main_body_114",
    "main_body_115",
    "main_body_116",
    "main_body_117",
    "main_body_118",
    "main_body_119",
    "main_body_120",
    "main_body_121",
    "main_body_122",
    "main_body_123",
    "main_body_124",
    "main_body_125",
    "main_scene_126",
    "main_scene_127",
    "main_scene_128",
    "main_scene_129",
    "main_scene_130",
    "main_scene_131",
    "main_scene_132",
    "main_scene_133",
    "main_scene_134",
    "main_scene_135",
    "main_scene_136",
    "main_scene_137",
    "main_scene_138",
    "main_scene_139",
    "main_scene_140",
    "main_scene_141",
    "main_scene_142",
    "main_scene_143",
    "main_scene_144",
    "main_scene_145",
    "main_scene_146",
    "main_scene_147",
    "main_scene_148",
    "main_scene_149",
    "main_scene_150",
    "main_object_151",
    "main_object_152",
    "main_object_153",
    "main_object_154",
    "main_object_155",
    "main_object_156",
    "main_object_157",
    "main_object_158",
    "main_object_159",
    "main_object_160",
    "main_object_161",
    "main_object_162",
    "main_object_163",
    "main_object_164",
    "main_object_165",
    "main_object_166",
    "main_object_167",
    "main_object_168",
    "main_object_169",
    "main_object_170",
    "main_object_171",
    "main_object_172",
    "main_object_173",
    "main_object_174",
    "main_object_175",
    "main_object_176",
    "main_object_177",
    "main_object_178",
    "main_object_179",
    "main_object_180",
    "main_object_181",
    "main_object_182",
    "main_object_183",
    "main_object_184",
    "main_object_185",
]